### ISSUE TITLE
OCamlコードでJSONをパースする

### ISSUE THREAD

**Issue by corvvs** [corvvs/turrrr#7]
まずは調査

**Comment by kotabrog** [comment]
https://camlspotter.hatenablog.com/entry/20121211/1355239314
こんなのありました（中身はちゃんと読めてないですが、とっても簡単そうにやってる）

**Comment by corvvs** [comment]
> https://camlspotter.hatenablog.com/entry/20121211/1355239314 こんなのありました（中身はちゃんと読めてないですが、とっても簡単そうにやってる）

なんか高級そうなことしてますねー

**Comment by corvvs** [comment]
`opam install`がダウンロードエラーで失敗・・・
→ `brew upgrade wget`で解消。
